remove javatest code and add maven javatest dependency.
jtulach/netbeans-apitest pull request #5
Opened 2021-11-12 11:43 UTC by gurunrao

remove javatest code and add maven javatest dependency.
Motivation for PR is: `javatest.jar should have Status.java[ as it currently have] and not sigtest.jar, hence have made changes for removal of javatest code[ Status.java, Test.java] and add javatest dependency to the pom.xml, which resolves the issue.`
Signed-off-by: gurunandan.rao@oracle.com <gurunandan.rao@oracle.com>

2021-11-12 17:01 UTC, JaroslavTulach requested changes

2021-11-12 17:01 UTC, JaroslavTulach commented on pom.xml
> +        <dependency>
I don't want a dependency on `com.sun/javatest` - that needlessly increases the [weight of this JAR](http://wiki.apidesign.org/wiki/HeavyWeight). Rather than that, please delete `com.sun.tdk.signaturetest.Test` as well. Users of my SigTest aren't interested in JCK stuff, I hope.

2021-11-13 16:36 UTC, gurunrao commented on pom.xml
> +        <dependency>
done

2021-11-15 05:34 UTC, jtulach commented
Great, thank you!

2021-11-15 05:35 UTC, merged

2021-11-16 02:46 UTC, jtulach commented
I am trying to publish new version, but maven.java.net seems to face "gateway timeout" issues for the last two days.